import type { Metadata } from "next";
//import CssBaseline from "@mui/material/CssBaseline";
import "./globals.css";
//import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
//

import { Roboto } from "next/font/google";
import Providers from "./providers";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});
/* add roboto fonts */
/* import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css"; */

export const metadata: Metadata = {
  title: "RHF",
  description: "Generated by Ahmed Esmail",
};

//const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

/* 

 <QueryClientProvider client={queryClient}>
          
        </QueryClientProvider>

*/
